[global]

# By default, Streamlit checks if the Python watchdog module is available and, if not,
# prints a warning asking for you to install it. The watchdog module is not required,
# but highly recommended. It improves the user experience by monitoring changes in your
# source files and automatically reloading the app when they change.
disableWatchdogWarning = false

# If True, will show a warning when you run a Streamlit-enabled script via "python my_script.py".
showWarningOnDirectExecution = true

# DataFrame serialization.
dataFrameSerialization = "legacy"

[logger]

# Level of logging: 'error', 'warning', 'info', or 'debug'.
level = "info"

# String format for logging messages. If logger.datetimeFormat is set, logger messages
# will default to `%(asctime)s.%(msecs)03d %(name)s: %(levelname)s: %(message)s`.
# See [Python's documentation](https://docs.python.org/2.6/library/logging.html#formatter-objects)
# for available attributes.
messageFormat = "%(asctime)s %(message)s"

[client]

# Whether to enable st.cache.
caching = true

# If false, makes your Streamlit script not connect to the Streamlit servers.
showErrorDetails = true

[browser]

# Internet address where users should point their browsers in order to connect to
# the app. Can be IP address or DNS name and path.
serverAddress = "localhost"

# Whether to send usage statistics to Streamlit.
gatherUsageStats = false

# Port where users can connect to the app.
serverPort = 8501

[server]

# List of folders that should not be watched for changes. This impacts both
# "Run on Save" and @st.cache.
folderWatchBlacklist = []

# Change the type of file watcher used by Streamlit, or turn it off completely.
fileWatcherType = "auto"

# Symmetric key used to produce signed cookies. If deploying on multiple replicas,
# ensure that this is set to the same value across all replicas to ensure they all
# share the same secret.
cookieSecret = "openai_token_calculator_secret_key"

# If false, will attempt to open a browser window on start.
headless = false

# Automatically rerun script when the file is modified on disk.
runOnSave = true

# The address on which the server will listen for client and browser connections.
address = "localhost"

# The port on which the server will listen for client and browser connections.
port = 8501

# Enables support for Cross-Origin Request Sharing (CORS) protection, for added security.
enableCORS = false

# Enables support for Cross-Site Request Forgery (XSRF) protection, for added security.
enableXsrfProtection = true

# Max size, in MB, for the auto-generated hashed_func_cache.
maxUploadSize = 200

# Max size, in MB, of messages that can be sent via the WebSocket connection.
maxMessageSize = 200

# Enables support for websocket compression.
enableWebsocketCompression = false

[theme]

# Primary accent color for interactive elements.
primaryColor = "#1E90FF"

# Background color for the main content area.
backgroundColor = "#FFFFFF"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#F0F2F6"

# Color used for almost all text.
textColor = "#262730"

# Font family for all text in the app, except code blocks.
font = "sans serif" 